name: releaseAll
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACK_NAME: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.0
          cache: pip
          architecture: x64
      #- name: Setup Python Package
      #  run: |
      #    cd ./script/
      #    python -m pip install --upgrade pip
      #    python -m pip install -r requirements.txt
      #    cd ..
      - name: Run release_all.py
        run: |
          python ./script/release_all.py
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./all.txt
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: Github CI
          message: '[Bot] Update All'
          push: true
          # tag_push: '--force'
